### ISSUE TITLE
Suggestion: Propose list of mediator when creating a new mediation case

### ISSUE THREAD

**Issue by Lauchan21** [Loxe-Inc/mediators.ai-qa#4]
When creating a new mediation case, once the day and date is confirmed, it would be nice to have an extra step and have a dropdown list of mediators (maybe the ones matching the mediation area + selected day and time) for the user to choose from. 

The list could for example be based on user ranting (e.g. 5 stars rated mediator first), location, etc.

Alternatively a search feature with full list of mediators could be placed on the left side (e.g. Below My Account) on the main page. User could then search mediator by: Name, Mediation area, ranking, number of mediation processed, etc...

**Comment by manonthemat** [comment]
Thanks for your suggestion. This was the initial design, but we have then since moved to a more seamless experience in that the selection of the mediator happens on the backend. Just like you don't select your driver for lyft/uber to get safely from point A to point B, the mediator will be selected on the parameters the disputing parties provide.
